<section class="row">
            <div class="col-12">
                <h1>Eric</h1>
                <p style="color: red;">Mon Porte-Folio</p>
            </div>
            <div class="col-12 col-md-6">
                
                <h2>Mon passé</h2>
                <p>
                    J'ai commencée a coder a 12 ans <br>
                    effectivement, le premier language est le batch <br>
                    après j'ai toucher au java-script, pour les bots discord avec JS <br>
                    Puis j'avais plein d'idée , j'ai donc fais du  html css pour coder mon premier site <br>
                    puis voulant toucher a minecraft, j'appris le python pour commencer dans le dur <br>
                    j'ai toujours voulu etre un crack <br>
                    j'ai aussi acquis des connaissances sur linux, et appris la gestion de server, avec les proxis <br>
                    j'ai toujours eu envie de faire des gros projects mais j'ai pas assez de connaissances<br>
                </p>
            </div>
            <div class="col-12 col-md-6">
                <h2>Actuellement</h2>
                <div class="col">
                    Actuellement je travaille en tant que castreur de maïs <br>
                    je suis en stage en informatique
                <hr>
                <img src="./images/codehtml.png" class="rounded float-end img-fluid" alt="code">
                </div>
            </div>
            <hr>
        </section>
        
        <section class="row">
            <div class="col-12">
                <h2>Les languages de <strong>programmation</strong> tester</h2>
            </div>
            
            <div class="col-12 col-md-6 col-lg-3">

                <div class="card" id="meslanguages1"> 
                    <div class="card-body">
                        <h2 class="card-title text-center">premier language</h2>
                        <h6 class="card-subtitle mb-2 text-body-secondary">html css</h6>
                        <h5 class="card-text"><a class="btn btn-outline-success" href="./lang_py.html#html">cliquer pour voir les infos</a></h5>
                        <img class="card-img-top" src="images/htmlcss.png" alt="logo1">
                    </div>
                </div>
            </div>
            <div class="col-12 col-md-6 col-lg-3">
                <div class="card" id="meslanguages2"> 
                    <div class="card-body">
                        <h2 class="card-title text-center">deuxieme language</h2>
                        <h6 class="card-subtitle mb-2 text-body-secondary">batch</h6>
                        <h5 class="cardtext"><a class="btn btn-outline-success" href="./lang_py.html#batch">cliquer pour voir les infos</a></h6>
                        <img src="images/batch.jpeg" class="card-img-top" style="width: 37%;" alt="logo2">
                    </div>
                </div>
            </div>
            <div class="col-12 col-md-6 col-lg-3" style="width: 25%;">
                <div class="card" id="meslanguages3"> 
                    <div class="card-body">
                        <h2 class="card-title text-center">troisième language</h2>
                        <h6 class="card-subtitle mb-2 text-body-secondary">JS</h6>
                        <h5 class="card-text"><a class="btn btn-outline-success" href="./lang_py.html#js">cliquer pour voir les infos</a></h5>
                        <img src="images/JS.png" class="card-img-top" alt="logo3" style="width: 67%;">
                    </div>
                </div>
            </div>
            <div class="col-12 col-md-6 col-lg-3" style="width: 25%;">
                <div class="card" id="meslanguages4"> 
                    <div class="card-body">
                        <h2 class="card-title text-center">Quatrieme language</h2> 
                    <h6 class="card-subtitle mb-2 text-body-secondary">python</h6>
                    <h5 class="card-text"><a class="btn btn-outline-success" href="./lang_py.html#python">cliquer pour voir les infos</a></h5>
                    <img src="images/python.png" class="card-img-top" alt="logo4" style="width: 55%;">
                    </div>
                </div>

            </div>            
        </section>