<section class="row">
    <div class="col-12 col-md-6">
        <h1>Mes infos</h1>
        <hr style="width: 50%;">
        <div class="card col-12" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">Mon mail</h5>
                <h6 class="card-subtitle mb-2 text-body-secondary"><span class="badge text-bg-secondary">Eric Garnier</span></h1></h6>

                <p class="card-text">cliquer pour envoyé un mail a Eric</p>
                <a href="mailto:e.garnier79400@gmail.com" class="card-link btn btn-primary">ecrire un mail</a>
            </div>
                <div">
                    <div class="card-body">
                        <h5 class="card-title">Mon discord</h5>
                        <h6 class="card-subtitle mb-2 text-body-secondary"><span class="badge text-bg-secondary">Moustitique</span></h1></h6>
                        <p class="card-text">Venez parlez avec moi</p>
                        <a href="https://discord.gg/n5qEq7BaHP" class="card-link">mon server</a>
                    </div>
                </div>
            </div>
        <img class="img-thumbnail" style="width: 500px;" src="./images/cv.png" alt="cv">
    </div>
    <div>
        <iframe src="https://discord.com/widget?id=1023272076204838943&theme=dark" width="300" height="500" allowtransparency="true" frameborder="0" sandbox="allow-popups allow-popups-to-escape-sandbox allow-same-origin allow-scripts"></iframe>              
    </div>  
</section>
<br>
<section class="row">

</section>
