<section class="row">
    <div class="col-12 col-md-6">
        <h1>Mes infos</h1>
        <hr style="width: 50%;">
        <p>mon mail | e.garnier79400@gmail.com</p>
        <p>Mon discord | https://discord.gg/n5qEq7BaHP</p>
        <img class="img-thumbnail" style="width: 500px;" src="./images/cv.png" alt="cv">
    </div>
    <div class="col-12 col-md-6 d-flex justify-content-end">
        <iframe src="https://discord.com/widget?id=1023272076204838943&theme=dark" width="300" height="500" allowtransparency="true" frameborder="0" sandbox="allow-popups allow-popups-to-escape-sandbox allow-same-origin allow-scripts"></iframe>              
    </div>  
</section>
<br>
<section class="row">
    <div class="col-12 col-md-6">
        <img id="disc1" class="img-fluid" src="./images/bot.png" alt="bot">
    </div>
    <div class="col-12">
        <p>test</p>
    </div>
</section>
