
<div class="row">
    <div class="col-12 col-md-6">
        <img class="img-thumbnail" src="./images/5258892.jpg" alt="banner">
    </div>
    <div class="col-12 col-md-6">
        <ul class="list-group">
            <li class="list-group-item active" aria-checked="true">Les différents Languages Informatiques</li>
            <li class="list-group-item">Doc Html Css boostrap <button type="button" class="btn btn-warning"><a href="https://getbootstrap.com/docs/5.3/getting-started/introduction/">ici</a></button></li>
            <li class="list-group-item">Doc batch <button type="button" class="btn btn-warning"><a href="https://en.wikibooks.org/wiki/Windows_Batch_Scripting">ici</a></button></li>
            <li class="list-group-item">Doc JS <button type="button" class="btn btn-warning"><a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript">ici</a></button></li>
            <li class="list-group-item">Doc python <button type="button" class="btn btn-warning"><a href="https://youtube.com/playlist?list=PLomHwoldFLYNIabPicgSOFS2KzuaeeOIu&si=IfR32Boi_H_1KbEZ">ici</a></button></li>
        </ul>
    </div>
</div>
<br>
<section class="row">
    <div class="col-6 col-md-6">
        <div class="accordion" id="accordionExample">
            <div class="accordion-item">
                <h2 class="accordion-header">
                    <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                        Premier Projects, <b>Un Server Minecraft</b>
                    </button>
                </h2>
                <div id="collapseOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample">
                    <div class="accordion-body">
                        <p>Le projet de ma vie d'ados</p><hr>
                        <p>
                            Comment j'en suis arrivée a cette idée ?<br>
                            Comment j'ai fais et avec quelles config ?
                            Quelle moyen j'ai utilisé pour pouvoir réussir ?
                        </p>
                        <button class="btn btn-primary">
                            <a style="color: black;" href="#project1">En savoir Plus</a>
                        </button>
                    </div>
                </div>
            </div>
            <div class="accordion-item">
                <h2 class="accordion-header">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                        Deuxiemes projects: <b>Dev Mini launcher Minecraft</b>
                    </button>
                </h2>
                <div id="collapseTwo" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
                    <div class="accordion-body">
                        <p>L'avancement du projet</p><hr>
                        <p>
                            Quelle moyen j'ai utilisée ?
                            Avec quelle languages de programmation ?
                            Les differents support que j'ai utilisée
                        </p>
                        <button class="btn btn-primary">
                            <a style="color: black;" href="#project2">En savoir Plus</a>
                        </button>
                    </div>
                </div>
            </div> 
            <div class="accordion-item">
                <h2 class="accordion-header">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTree" aria-expanded="false" aria-controls="collapseTwo">
                        Troisième projet: <b>Discord bot</b>
                    </button>
                </h2>
                <div id="collapseTree" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
                    <div class="accordion-body">
                        <p>Un bot discord a l'ancienne</p><hr>
                        <p>
                            Quelle techno j'ai utiliser ?
                            Quelle moyen j'ai mobiliser ?
                            Discord est-il bien ?

                        </p>
                        <button class="btn btn-primary">
                            <a style="color: black;" href="#project3">En savoir Plus</a>
                        </button>
                    </div>
                </div>
            </div> 
            <div class="accordion-item">
                <h2 class="accordion-header">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapsefours" aria-expanded="false" aria-controls="collapseTwo">
                        Quatrieme projet: <b>La programmation générale</b>
                    </button>
                </h2>
                <div id="collapsefours" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
                    <div class="accordion-body">
                        <p>Pourquoi programmer</p><hr>
                        <p>
                            Comment je me suis lancez ?
                            Pourquoi sa et pas autre chose ?
                            Comment j'ai fais ? 
                        </p>
                        <button class="btn btn-primary">
                            <a style="color: black;" href="#PreServ4">En savoir Plus</a>
                        </button>
                    </div>
                </div>
            </div>
            <div class="accordion-item">
                <h2 class="accordion-header">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapsefive" aria-expanded="false" aria-controls="collapseTwo">
                        Cinquième projet: <b>Mon future</b>
                    </button>
                </h2>
                <div id="collapsefive" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
                    <div class="accordion-body">
                        <p>Ce que je veux plus tard</p><hr>
                        <p>
                            Quelles idée j'ai ?
                            Comment je vais faire ?
                            Quelles moyen technique je vais utiliser ?
                        </p>
                        <button class="btn btn-primary">
                            <a style="color: black;" href="#project5">En savoir Plus</a>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="5012" class="col-6" offset-12>
        <div class="col-12">
            <button type="button" class="rounded float-start btn" style="width: 45%;">
                <img  class="img-thumbnail" src="./images/skin.png" alt="skin">
                <p><strong>Mon skin</strong></p>
            </button>
            <button class="rounded float-end btn" type="button" style="width: 45%;">
                <img class="img-thumbnail" src="./images/ordi.jpeg" alt="ordi">
                <p><strong>Les ancien pc</strong></p>
            </button> 
        </div>
    </div>
</section>
<br>
<section id="project1" class="row">
    <div>
        <div>
            <h2>
                Le projet de ma vie d'ados
            </h2><hr>
            <div>
                <ul>
                    <li>L'ensmble d'un gros projet</li>
                </ul>
                <p>
                    Il y a quelque temps , j'ai voulu lancez mon propre server Minecraft
                    J'vais vu les autres faire, ainsi que des youtubeur et j'ai voulu faire la meme
                    Le server avec 1 quart des fonctionnalités requise, le themes : "minerais de sang",
                    une multitude de plugin pour configurer le server
                    et une modification des parametre dans les fichier, aussi la gestion du bungeecord
                    c'est tous un art de faire fonctionner des servers, je comprend pourquoi il y a une équipe entiere pour créer ce genre de projects
                    (j'ai passer des nuits sur des bugs, ou a modifier les configs pour s'adapter a mon style)
                    encore aujourd'hui j'apprend , et je veux réaliser ce reves de gosse quand je serais grand
                </p>
            </div>
            <div class="col-6 offset-12">
                <iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/80H8afCf8xw?si=Dgu93co3EH4askcu" title="Tuto" frameborder="0"  autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
            </div>
        </div>
    </div>   
</section>
<hr style="border: 20px;">
<section id="project2" class=" row">
    <h2>
        <span class="badge text-bg-primary">La suite: Le Developpement d'un mini launcher Minecraft</span>
    </h2><hr>
    <ul>
        <li>Nouvel experiences de codage avec python</li>
    </ul>
    <p>
        pour commencer, je suis passer par plusieur étape
        l'api du launcher , c'est a dire dévellopper le téléchargement des fichier, avec un system de fichier json principalement , avec comme intégration la modification du nom et de l'id (mode crack) .
        Pas de premium car mojang fais payer les tokens de connexion
        ensuite une fois le cli de fais
        il faut faire l'ui 
        customtkinter pour l'ui
        les modules utilisé principalement sont : os, json, mcpi ou minecraft_python
        le logiciel assez simple a prendre en main, avec une interface minimaliste mais fonctionnel
        pas de possibilité de rejoindre les server premium 
        monde solo oui, ainsi que les servers crack
    </p>
    <p>
        d'autre launcher comme Tlauncher , Azlauncher sont possible au crack
        attention, ne télécharger pas n'importe quoi sur internet
    </p>
    <button class="btn btn-danger" type="button">
        toujours regardez l'authenticiter et la securiter du site web, avec notamment le "https" et le cadenas, ainsi que les RGPD , les TERMS, la Privacy page et la security page
    </button>   
</section>
<hr style="border: 20px;">
<section id="project3" class="row">
    <h2>
        <span class="badge text-bg-primary">Pourquoi Programmer</span> 
    </h2><hr>
    <div>
        <ul>
            <li>j'aime les ordi</li>
        </ul>
        <p>
            Quand j'était petit mon père avais un ordinateur avec windows xp -> ci joint la photo au dessus <button class="btn btn-warning" type="button"><a href="#5012">ici</a></button>
            tout de suite j'ai trouver sa hyper cool
            quand j'ai reçus mon premier pc j'ai beacoup geeker
            et puis j'avais envie d'apprendre a creer des choses moi aussi 
            je voyais tout le monde jouez a minecraft avec des fonctionnalité super cool , j'ai donc essayer de cracker le jeux
            au final je réussi apres des jours de recherche acharné
            grace a un ami , j'ai fais mon premier site web static sur le fichier text de windows, sans quelconque aide
            puis j'ai appris le python pour pouvoir step up mon experiences
            python permet de faire des mini app, des calculs monstrueux , des api ect
            aujoud'hui j'ai la determination de faire de la programmation mon travail 
            j'ai sa et sa ma toujours plus 
            et je serais pret a tous pour réussir
        </p>
</section>
    <section id="project4" class="row">
<h2>
    <span class="badge text-bg-primary">Discord</span>
</h2><hr>
<div>
    <ul>
        <li>Ancien de discord</li>
    </ul>
    <p>
        j'ai connu discord en <span class="badge text-bg-secondary">2019</span>
        j'ai devellopper mon premier bot pour m'amuser
        il pouvais faire des commandes simple type "!test"
        aujoud'hui c'est avec un "/"
        j'analysais le source code de MEE6 avant d'etre bloquer et aujourd'hui je ne serais pas capable de dev ce que j'ai fais a l'époque du au changement de la societe , options tous réapprendre 
        bon debut de base en programmation , je me suis amuser
    </p>
</section>
<hr style="border: 20px;">
